config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#index' # Ruta raíz, puedes cambiarla según tus necesidades

  # Rutas de autenticación personalizada
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :articles, only: [:index, :new, :show, :create, :destroy] do
    resources :commentaires, only: [:index, :new, :show, :create, :destroy] # Esto define rutas anidadas para los comentarios dentro de los artículos

    # Rutas estándar RESTful
    collection do
      get :new, action: :new, as: :new_article
      post :create, action: :create, as: :create_article
    end
    member do
      get :show, action: :show, as: :show_article
      get :edit, action: :edit, as: :edit_article
      patch :update, action: :update, as: :update_article
      delete :destroy, action: :destroy, as: :destroy_article
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :commentaires, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
  URL_REGEXP = /(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?/ix
  validates :banner_url, format: { with: URL_REGEXP, message: 'format invalid' }
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :name, presence: true, uniqueness: { scope: :article_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :commentaires
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!

  def index

    @articles = Article.all
    @articles = Article.first
    @commentaires = current_user.commentaires
  end


  def show
    @article = Article.find_by_id(params[:id])

    if @article
      @commentaire = Commentaire.new
      @commentaires = @article.commentaires
    else
      # Maneja el caso en el que no se encuentra el artículo
      flash[:error] = "El artículo no se encontró"
      redirect_to root_path # O cualquier otra ruta adecuada
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def article_params
    params.require(:article).permit(:name, :banner_url, :description) # Agregar `:` antes de `description`
  end
end

app/controllers/commentaires_controller.rb
class CommentairesController < ApplicationController
  def new
    @article = Article.find(params[:article_id])
    @commentaire = Commentaire.new
  end

  def create
    @article = Article.find(params[:article_id])
    @commentaire = Commentaire.new(commentaire_params)
    @commentaire.article = @article
    if @commentaire.save
      redirect_to article_path(@article), notice: 'Comentario creado exitosamente.'
    else
      render 'articles/show', status: :unprocessable_entity
    end
  end

  def edit
    @commentaire = Commentaire.find(params[:id])
  end

  def update
    @commentaire = Commentaire.find(params[:id])
    if @commentaire.update(commentaire_params)
      redirect_to article_path(@commentaire.article), notice: 'Comentario actualizado exitosamente.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @commentaire = Commentaire.find(params[:id])
    @article = @commentaire.article
    if @commentaire.destroy
      redirect_to article_path(@article), notice: 'Comentario eliminado exitosamente.'
    else
      redirect_to article_path(@article), alert: 'No se pudo eliminar el comentario.'
    end
  end

  # ...

  private

  def commentaire_params
    params.require(:commentaire).permit(:name, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = Session.new
  end

  def create
    # Encuentra al usuario por su dirección de correo electrónico
    user = User.find_by(email: params[:session][:email])

    # Verifica si el usuario existe y si la contraseña es válida
    if user && user.authenticate(params[:session][:password])
      # Inicia sesión al usuario
      log_in user

      # Redirige a una página después de iniciar sesión (por ejemplo, la página de perfil)
      redirect_to user
    else
      # Muestra un mensaje de error y vuelve al formulario de inicio de sesión
      flash.now[:danger] = 'Dirección de correo electrónico o contraseña incorrecta.'
      render 'new'
    end
  end


  def destroy
    # Cierra la sesión del usuario
    log_out if logged_in

    # Redirige a una página después de cerrar sesión (por ejemplo, la página de inicio)
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/commentaires_helper.rb
module CommentairesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_article_card.html.erb
<%= link_to article_path(article_id) do %>
  <div class="card-article">
    <%= image_tag article.banner_url %>
    <div class="card-article-infos">
      <div>
        <h2><%= article.name %></h2>
        <p><%= article.description %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_articles_card.html.erb
<%= link_to article_path(article) do %>
  <div class="card-article">
    <%= image_tag article.banner_url %>
    <div class="card-article-infos">
      <div>
        <h2><%= article.name %></h2>
        <p><%= article.description %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_commentaire_card.html.erb
<div class="card-plant" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= commentaire.name %>')">
  <%= commentaire.name %>
  <%= commentaire.description %>
  <%= link_to "+", article_commentaire_path(commentaire), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "card-remove-link" %>
  <%= link_to "Volver", article_path(commentaire), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "card-remove-link" %>
</div>

app/views/articles/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url(<%= image_path('home_banner.jpg') %>)">
  <div class="container">
    <h1>Information</h1>
    <p>A tout moment!</p>
    <%= link_to "View All Articles", articles_path, class: "btn btn-flat" %>
  </div>
</div>

<div class="container">
  <div class="section">
    <h2 id="how" class="text-center">How does it work?</h2>
    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_article_path do %>
          <div class="icon">
            <%= image_tag "article.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Create your article</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_article_path do %>
          <div class="icon">
            <%= image_tag "circles.svg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>



    </div>
  </div>
  <div class="section">
    <div class="text-center">
      <%= link_to "Create my article", new_article_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="pt-30 container">
  <h1 class="text-center">New Aricle</h1>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@article) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :banner_url %>
          <%= f.input :description %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @article_id.banner_url %>')">
  <div class="container">
    <h1><%= @article.name %></h1>
  </div>
</div>

<div class="pt-30 container">
  <div class="cards">
    <% @article.commentaires.each do |commentaire| %>
      <%= render "articles/commentaire_card", commentaire: commentaire %>
    <% end %>
  </div>

  <div class="pt-30 row justify-content-center">
    <div class="col-12 col-md-4">
      <h4 class="text-center">Add a commentaire</h4>
        <%= simple_form_for [ @article, @commentaire ] do |f| %>
        <%= f.input :name, placeholder: "je suis d'accord" %>
        <%= f.input :description, placeholder: "Liberez vous" %>
        <%= f.button :submit, "Add Commentaire" %>
        <div class="form-actions">
          <%= f.submit "Add", class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- articles/show.html.erb -->
<h1><%= @article.name %></h1>
<p><%= @article.description %></p>

<h2>Comentarios</h2>
<ul>
  <% @article.commentaires.each do |commentaire| %>
    <li>
      <strong><%= commentaire.name %></strong>
      <p><%= commentaire.description %></p>
      <%= link_to 'Editar', edit_commentaire_path(commentaire) %>
      <%= link_to 'Borrar', commentaire, method: :delete, data: { confirm: '¿Estás seguro?' } %>
    </li>
  <% end %>
</ul>

<h2>Nuevo Comentario</h2>
<%= render 'commentaires/form' %>

app/views/commentaires/_form.html.erb
<!-- commentaires/_form.html.erb -->
<%= simple_form_for([@article, @commentaire]) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/commentaires/_form_for_activity.html.erb
<%= simple_form_for(@commentaire, url: commentaire_path(@commentaire), method: :put) do |f| %>

  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit, "Comment", class: "btn btn-flat" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Information</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/Valeria-Pallas"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at La Lune
  </div>
</div>

app/views/shared/_navbar.html.erb
</div>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon container-fluid">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="logo">
      <%= image_tag "https://cdn.pixabay.com/photo/2019/07/10/09/09/animal-world-4328243_1280.jpg" %>
    </div>
  <% end %>

  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <!-- Si el usuario está autenticado, muestra un enlace para cerrar sesión -->
      <li class="nav-item">
        <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    <% else %>
      <!-- Si el usuario no está autenticado, muestra enlaces para iniciar sesión y registrarse -->
      <li class="nav-item">
        <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Registrarse", new_user_registration_path, class: "nav-link" %>
      </li>
    <% end %>
  </ul>
</div>